name: Pruebas

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  construir-y-probar:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Descargar Catch2
      run: |
        mkdir externos
        wget https://github.com/catchorg/Catch2/releases/download/v3.0.1/catch2-v3.0.1.zip -O extern/catch2.zip
        unzip extern/catch2.zip -d externos/Catch2
    - name: Compilar
      run: |
        cmake -S . -B build
        cmake --build build
    - name: EjecutarPruebas
      id: test
      run: |
        build\correr_pruebas.exe -s
    - name: VerificarResultadosPruebas
      if: steps.test.outcome != 'success'
      run: |
        echo "::set-output name=test_output::$(cat $GITHUB_WORKSPACE/build/Testing/Temporary/LastTest.log)"
    - name: EstablecerEstadoPR
      uses: actions/github-script@v6
      with:
        script: |
          const result = ${{ steps.test.outcome }};
          const output = result == 'success' ? 'Las pruebas pasaron correctamente' : context.workflow.steps.check_test_result.outputs.test_output;
          github.rest.repos.createCommitStatus({
            ...context.repo,
            sha: context.sha,
            state: result,
            description: output,
            context: 'Resultados de las pruebas'
          });
